sudo: false
language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
before_install:  mkdir ~/.npm-global && npm config set prefix '~/.npm-global' && export PATH=~/.npm-global/bin:$PATH && source ~/.profile
script: npm test
after_success: npm install -g grunt-cli yo bower && npm link && mkdir testrun && cd testrun &&  yo atomic testProk test TestRunner less true true true && grunt build
email:
    on_success: never # default: change
    on_failure: change # default: always
